language: ruby
rvm:
  - 2.4
script:
  - cd MiniTest; bundle install; bundle exec rspec -fd; cd ..
  - cd CodeQuizzes; bundle install; bundle exec rspec -fd; cd ..
  - cd InsertionSort; bundle install; bundle exec rspec -fd; cd ..
